# Generated by Django 5.0.4 on 2024-04-30 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_site', '0002_movie_director_alter_movie_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kino_site.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
