# Generated by Django 5.0.4 on 2024-05-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_site', '0003_genre_category_alter_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='draft_en',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='movie',
            name='draft_ru',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_en',
            field=models.ImageField(null=True, upload_to='movies/', verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_ru',
            field=models.ImageField(null=True, upload_to='movies/', verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
