# Generated by Django 5.0.4 on 2024-05-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino_site', '0004_movie_description_en_movie_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='draft_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='draft_ru',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_ru',
        ),
    ]
